name: Deploy AWS Infra with Terraform

on:
  push:
    branches:
      - main   # runs on pushes to main branch
  workflow_dispatch:   # allow manual trigger

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1

    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

     - name: Store AWS Credentials Securely
        run: |
          echo "AWS_ACCOUNT_ID=118293630210" >> $GITHUB_ENV
          echo "AWS_REGION=us-east-1" >> $GITHUB_ENV
          echo "AWS_ACCESS_KEY_ID=AKIARXCWZRUBEHHT2NO5" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=sgWRMLvT3334RpzJToYZfJx2fJLdQDs7QkRQ8M" >> $GITHUB_ENV
          echo "$GITHUB_ENV"

      # 2. Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # 3. Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      # 4. Terraform Init
      - name: Terraform Init
        run: terraform init

      # 5. Terraform Plan
      - name: Terraform Plan
        run: terraform plan -out=tfplan

      # 6. Terraform Apply (auto-approve)
      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
